### ISSUE TITLE
regional_unit layer download not working

### ISSUE THREAD

**Issue by domisch** [glowabio/hydrographr#32]
The "regional_unit" layer can not be downloaded with download_tiles(). The function retaurs nothing, saying  "Download size is 0 MB."
Also, maybe a name-check could be useful, to tell the user if a given name is not available for download (or the user has a has a typo etc)

**Comment by afrogri37** [comment]
You need to specify the reg_unit_id, obtained with the function get_regional_unit_id(). 
download_tiles(variable = "regional_unit", file_format = "tif", download_dir = ".", reg_unit_id = "1")
or set global = TRUE, in case you need the global regional unit layer.
