### ISSUE TITLE
download test data / unzip not working on Windows

### ISSUE THREAD

**Issue by domisch** [glowabio/hydrographr#50]
The data is downloaded but unzip results in an empty directory:
Warning message:
In unzip(paste0(download_dir, "/hydrography90m_test_data.zip"),  :
  error 1 in extracting from zip file

The download should also use public.igb-berlin.de as the primary source

**Comment by mueblacker** [comment]
I have the same problem on Linux. Downloading and unzipping the folder manually works fine.  When I download the folder with R and then try to unzip it, I get the error message: "An error occurred while loading the archive".

**Comment by domisch** [comment]
I copied the test data to the IGB repository and this link should be the primary download source:
https://public.igb-berlin.de/index.php/s/9XGDD3EmHTs69g8

**Comment by merretbuurman** [comment]
Hi! I fixed this, branch `fix_download_test_data`. 
Sami, with the link you specify, when downloading in R you get a file containing HTML ("This application requires JavaScript for correct operation. Please enable JavaScript and reload the page."), it works if you put `/download` at the end: https://public.igb-berlin.de/index.php/s/9XGDD3EmHTs69g8/download.

https://github.com/glowabio/hydrographr/pull/59

**Comment by merretbuurman** [comment]
Fixed this in PR #59 which we merged yesterday.
https://github.com/glowabio/hydrographr/pull/59
