### ISSUE TITLE
caching the downloaded data. 

### ISSUE THREAD

**Issue by AnthonyBasooma** [glowabio/hydrographr#65]
When I run the **download_tile** function, the data is saved on the disk but still re-downloaded on the second attempt. Is there a possibility to check if the data is already downloaded and skipped?

**Comment by merretbuurman** [comment]
Dear Anthony! Thanks for posting the issue. We discussed this in the group, but apparently it sometimes happens that files on disk are moved or corrupted or other things. In that case it is better to redownload, so we decided to keep the download. If you know that you have already downloaded the data, you could comment the line, or separate download script from analysis script.
