### ISSUE TITLE
executing get_distance returns an error on windows for the Case study - São Francisco drainage basin

### ISSUE THREAD

**Issue by AnthonyBasooma** [glowabio/hydrographr#66]
network_distance <- get_distance(data = upstream_point_locations,
                                  lon = "lon_snap_accu",
                                lat = "lat_snap_accu",
                                  id = "site_id",
                                 stream_layer = upstream_segment_vect,
                                distance = "network",
                                  n_cores = 1)

**Error in `processx::run(system.file("bat", "get_distance.bat", package = "hydrographr"), …`:
! System command 'get_distance.bat' failed
---
Exit status: 126
Stderr:
dos2unix: converting file /mnt/c/Users/ANTHBA~1/AppData/Local/Temp/RtmpiQvOF5/ids_asN1MJo8.csv to Unix format...
/mnt/c/Users/ANTHBA~1/AppData/Local/Temp/RtmpiQvOF5/distance: /mnt/c/Users/ANTHBA~1/AppData/Local/Temp/RtmpiQvOF5/distance: Is a directory**

**Comment by tomitho** [comment]
We resolved the issue with the latest update to the function.
